//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoContenido.ServicePagoJasecJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://principal/", ConfigurationName="ServicePagoJasecJava.electricidadJasec")]
    public interface electricidadJasec {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://principal/electricidadJasec/pagoRequest", ReplyAction="http://principal/electricidadJasec/pagoResponse")]
        BancoContenido.ServicePagoJasecJava.pagoResponse pago(BancoContenido.ServicePagoJasecJava.pagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://principal/electricidadJasec/pagoRequest", ReplyAction="http://principal/electricidadJasec/pagoResponse")]
        System.Threading.Tasks.Task<BancoContenido.ServicePagoJasecJava.pagoResponse> pagoAsync(BancoContenido.ServicePagoJasecJava.pagoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://principal/electricidadJasec/helloRequest", ReplyAction="http://principal/electricidadJasec/helloResponse")]
        BancoContenido.ServicePagoJasecJava.helloResponse hello(BancoContenido.ServicePagoJasecJava.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://principal/electricidadJasec/helloRequest", ReplyAction="http://principal/electricidadJasec/helloResponse")]
        System.Threading.Tasks.Task<BancoContenido.ServicePagoJasecJava.helloResponse> helloAsync(BancoContenido.ServicePagoJasecJava.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://principal/electricidadJasec/consultaRequest", ReplyAction="http://principal/electricidadJasec/consultaResponse")]
        BancoContenido.ServicePagoJasecJava.consultaResponse consulta(BancoContenido.ServicePagoJasecJava.consultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://principal/electricidadJasec/consultaRequest", ReplyAction="http://principal/electricidadJasec/consultaResponse")]
        System.Threading.Tasks.Task<BancoContenido.ServicePagoJasecJava.consultaResponse> consultaAsync(BancoContenido.ServicePagoJasecJava.consultaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pago", Namespace="http://principal/", Order=0)]
        public BancoContenido.ServicePagoJasecJava.pagoRequestBody Body;
        
        public pagoRequest() {
        }
        
        public pagoRequest(BancoContenido.ServicePagoJasecJava.pagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class pagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public pagoRequestBody() {
        }
        
        public pagoRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pagoResponse", Namespace="http://principal/", Order=0)]
        public BancoContenido.ServicePagoJasecJava.pagoResponseBody Body;
        
        public pagoResponse() {
        }
        
        public pagoResponse(BancoContenido.ServicePagoJasecJava.pagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class pagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public pagoResponseBody() {
        }
        
        public pagoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://principal/", Order=0)]
        public BancoContenido.ServicePagoJasecJava.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(BancoContenido.ServicePagoJasecJava.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://principal/", Order=0)]
        public BancoContenido.ServicePagoJasecJava.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(BancoContenido.ServicePagoJasecJava.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consulta", Namespace="http://principal/", Order=0)]
        public BancoContenido.ServicePagoJasecJava.consultaRequestBody Body;
        
        public consultaRequest() {
        }
        
        public consultaRequest(BancoContenido.ServicePagoJasecJava.consultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public consultaRequestBody() {
        }
        
        public consultaRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultaResponse", Namespace="http://principal/", Order=0)]
        public BancoContenido.ServicePagoJasecJava.consultaResponseBody Body;
        
        public consultaResponse() {
        }
        
        public consultaResponse(BancoContenido.ServicePagoJasecJava.consultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public consultaResponseBody() {
        }
        
        public consultaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface electricidadJasecChannel : BancoContenido.ServicePagoJasecJava.electricidadJasec, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class electricidadJasecClient : System.ServiceModel.ClientBase<BancoContenido.ServicePagoJasecJava.electricidadJasec>, BancoContenido.ServicePagoJasecJava.electricidadJasec {
        
        public electricidadJasecClient() {
        }
        
        public electricidadJasecClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public electricidadJasecClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public electricidadJasecClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public electricidadJasecClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancoContenido.ServicePagoJasecJava.pagoResponse BancoContenido.ServicePagoJasecJava.electricidadJasec.pago(BancoContenido.ServicePagoJasecJava.pagoRequest request) {
            return base.Channel.pago(request);
        }
        
        public string pago(string name) {
            BancoContenido.ServicePagoJasecJava.pagoRequest inValue = new BancoContenido.ServicePagoJasecJava.pagoRequest();
            inValue.Body = new BancoContenido.ServicePagoJasecJava.pagoRequestBody();
            inValue.Body.name = name;
            BancoContenido.ServicePagoJasecJava.pagoResponse retVal = ((BancoContenido.ServicePagoJasecJava.electricidadJasec)(this)).pago(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancoContenido.ServicePagoJasecJava.pagoResponse> BancoContenido.ServicePagoJasecJava.electricidadJasec.pagoAsync(BancoContenido.ServicePagoJasecJava.pagoRequest request) {
            return base.Channel.pagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancoContenido.ServicePagoJasecJava.pagoResponse> pagoAsync(string name) {
            BancoContenido.ServicePagoJasecJava.pagoRequest inValue = new BancoContenido.ServicePagoJasecJava.pagoRequest();
            inValue.Body = new BancoContenido.ServicePagoJasecJava.pagoRequestBody();
            inValue.Body.name = name;
            return ((BancoContenido.ServicePagoJasecJava.electricidadJasec)(this)).pagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancoContenido.ServicePagoJasecJava.helloResponse BancoContenido.ServicePagoJasecJava.electricidadJasec.hello(BancoContenido.ServicePagoJasecJava.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            BancoContenido.ServicePagoJasecJava.helloRequest inValue = new BancoContenido.ServicePagoJasecJava.helloRequest();
            inValue.Body = new BancoContenido.ServicePagoJasecJava.helloRequestBody();
            inValue.Body.name = name;
            BancoContenido.ServicePagoJasecJava.helloResponse retVal = ((BancoContenido.ServicePagoJasecJava.electricidadJasec)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancoContenido.ServicePagoJasecJava.helloResponse> BancoContenido.ServicePagoJasecJava.electricidadJasec.helloAsync(BancoContenido.ServicePagoJasecJava.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancoContenido.ServicePagoJasecJava.helloResponse> helloAsync(string name) {
            BancoContenido.ServicePagoJasecJava.helloRequest inValue = new BancoContenido.ServicePagoJasecJava.helloRequest();
            inValue.Body = new BancoContenido.ServicePagoJasecJava.helloRequestBody();
            inValue.Body.name = name;
            return ((BancoContenido.ServicePagoJasecJava.electricidadJasec)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancoContenido.ServicePagoJasecJava.consultaResponse BancoContenido.ServicePagoJasecJava.electricidadJasec.consulta(BancoContenido.ServicePagoJasecJava.consultaRequest request) {
            return base.Channel.consulta(request);
        }
        
        public string consulta(string name) {
            BancoContenido.ServicePagoJasecJava.consultaRequest inValue = new BancoContenido.ServicePagoJasecJava.consultaRequest();
            inValue.Body = new BancoContenido.ServicePagoJasecJava.consultaRequestBody();
            inValue.Body.name = name;
            BancoContenido.ServicePagoJasecJava.consultaResponse retVal = ((BancoContenido.ServicePagoJasecJava.electricidadJasec)(this)).consulta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancoContenido.ServicePagoJasecJava.consultaResponse> BancoContenido.ServicePagoJasecJava.electricidadJasec.consultaAsync(BancoContenido.ServicePagoJasecJava.consultaRequest request) {
            return base.Channel.consultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancoContenido.ServicePagoJasecJava.consultaResponse> consultaAsync(string name) {
            BancoContenido.ServicePagoJasecJava.consultaRequest inValue = new BancoContenido.ServicePagoJasecJava.consultaRequest();
            inValue.Body = new BancoContenido.ServicePagoJasecJava.consultaRequestBody();
            inValue.Body.name = name;
            return ((BancoContenido.ServicePagoJasecJava.electricidadJasec)(this)).consultaAsync(inValue);
        }
    }
}
