//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoContenido.ServiceTelefonoKolbi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTelefonoKolbi.IPagoTelefonoKolbi")]
    public interface IPagoTelefonoKolbi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoTelefonoKolbi/montopago", ReplyAction="http://tempuri.org/IPagoTelefonoKolbi/montopagoResponse")]
        string montopago(string medidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoTelefonoKolbi/montopago", ReplyAction="http://tempuri.org/IPagoTelefonoKolbi/montopagoResponse")]
        System.Threading.Tasks.Task<string> montopagoAsync(string medidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoTelefonoKolbi/pago", ReplyAction="http://tempuri.org/IPagoTelefonoKolbi/pagoResponse")]
        string pago(string medidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoTelefonoKolbi/pago", ReplyAction="http://tempuri.org/IPagoTelefonoKolbi/pagoResponse")]
        System.Threading.Tasks.Task<string> pagoAsync(string medidor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagoTelefonoKolbiChannel : BancoContenido.ServiceTelefonoKolbi.IPagoTelefonoKolbi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagoTelefonoKolbiClient : System.ServiceModel.ClientBase<BancoContenido.ServiceTelefonoKolbi.IPagoTelefonoKolbi>, BancoContenido.ServiceTelefonoKolbi.IPagoTelefonoKolbi {
        
        public PagoTelefonoKolbiClient() {
        }
        
        public PagoTelefonoKolbiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagoTelefonoKolbiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagoTelefonoKolbiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagoTelefonoKolbiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string montopago(string medidor) {
            return base.Channel.montopago(medidor);
        }
        
        public System.Threading.Tasks.Task<string> montopagoAsync(string medidor) {
            return base.Channel.montopagoAsync(medidor);
        }
        
        public string pago(string medidor) {
            return base.Channel.pago(medidor);
        }
        
        public System.Threading.Tasks.Task<string> pagoAsync(string medidor) {
            return base.Channel.pagoAsync(medidor);
        }
    }
}
