//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoContenido.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPagoElectricidadMuni")]
    public interface IPagoElectricidadMuni {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoElectricidadMuni/montopago", ReplyAction="http://tempuri.org/IPagoElectricidadMuni/montopagoResponse")]
        string montopago(string medidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoElectricidadMuni/montopago", ReplyAction="http://tempuri.org/IPagoElectricidadMuni/montopagoResponse")]
        System.Threading.Tasks.Task<string> montopagoAsync(string medidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoElectricidadMuni/pago", ReplyAction="http://tempuri.org/IPagoElectricidadMuni/pagoResponse")]
        string pago(string medidor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagoElectricidadMuni/pago", ReplyAction="http://tempuri.org/IPagoElectricidadMuni/pagoResponse")]
        System.Threading.Tasks.Task<string> pagoAsync(string medidor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagoElectricidadMuniChannel : BancoContenido.ServiceReference1.IPagoElectricidadMuni, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagoElectricidadMuniClient : System.ServiceModel.ClientBase<BancoContenido.ServiceReference1.IPagoElectricidadMuni>, BancoContenido.ServiceReference1.IPagoElectricidadMuni {
        
        public PagoElectricidadMuniClient() {
        }
        
        public PagoElectricidadMuniClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagoElectricidadMuniClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagoElectricidadMuniClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagoElectricidadMuniClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string montopago(string medidor) {
            return base.Channel.montopago(medidor);
        }
        
        public System.Threading.Tasks.Task<string> montopagoAsync(string medidor) {
            return base.Channel.montopagoAsync(medidor);
        }
        
        public string pago(string medidor) {
            return base.Channel.pago(medidor);
        }
        
        public System.Threading.Tasks.Task<string> pagoAsync(string medidor) {
            return base.Channel.pagoAsync(medidor);
        }
    }
}
